### ISSUE TITLE
 This could take a while. [really half an hour?]

### ISSUE THREAD

**Issue by telephon** [capital-G/musikinformatik-sose2021#13]
```
pip3 install -r requirements.txt
```

after a long chain of successes:

```
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
INFO: pip is looking at multiple versions of cloudpickle to determine which version is compatible with other requirements. This could take a while.
Collecting cloudpickle>=1.1.1
  Downloading cloudpickle-1.5.0-py3-none-any.whl (22 kB)
  Downloading cloudpickle-1.4.1-py3-none-any.whl (26 kB)
  Downloading cloudpickle-1.4.0-py3-none-any.whl (25 kB)
  Downloading cloudpickle-1.3.0-py2.py3-none-any.whl (26 kB)
  Downloading cloudpickle-1.2.2-py2.py3-none-any.whl (25 kB)
  Downloading cloudpickle-1.2.1-py2.py3-none-any.whl (25 kB)
  Downloading cloudpickle-1.2.0-py2.py3-none-any.whl (24 kB)
  Downloading cloudpickle-1.1.1-py2.py3-none-any.whl (17 kB)
```

no network traffic, just silent …

**Comment by capital-G** [comment]
@telephon : strange - is your internet connection fine? Maybe the connection got lost?
If this does not solve it you could delete the line `swifter` from `requirements.txt` as this introduces the dependency and I am not sure if I want to stick to this dependency.

**Comment by telephon** [comment]
Second attempt, it continues further …

**Comment by capital-G** [comment]
You have python3.8 on OSX or are you on python3.9?
The versioning of python is really sub-optimal on OSX, see https://xkcd.com/1987/

**Comment by telephon** [comment]
`Python 3.9.4`

**Comment by telephon** [comment]
but it could of course be that the python installed by xcode and the one installed by brew are in conflict. I don't know how to find out though.

Btw. the thing is stuck again as mentioned above.

**Comment by capital-G** [comment]
Then its most probably a python 3.9 issue, see https://github.com/capital-G/musikinformatik-sose2021/pull/14/files#diff-5040b2d3cc6419e41d11b6f615d99e61522958c202c336dcade3709f42448114R60-R67

**Comment by telephon** [comment]
```
brew install python@3.8

python@3.8 3.8.9 is already installed and up-to-date.
```

**Comment by telephon** [comment]
But `virtualenv --version`

in the root-folder gives me:
```
virtualenv 20.4.3 from /usr/local/Cellar/virtualenv/20.4.3/libexec/lib/python3.9/site-packages/virtualenv/__init__.py
```

so it seems it is using python3.9

**Comment by telephon** [comment]
I've reinstalled python 3.8 following the official guideline, but the same problem reappears.

**Comment by capital-G** [comment]
Sorry for the long journey.
It seems that python3.8 is not linked in your `PATH` variable.

A fix is to not use `python3` which is declared in your environment variable `PATH` to explicitly state the python executable you want to use during venv creation.
Assuming python@3.8 was indeed installed by homebrew and you are in the root directory of this cloned repository, then the following should work

```shell
# homebrew normally installs python here - check if it is indeed available
/usr/local/opt/python@3.8/bin/python3 --version
# lets make sure we start with a clean venv
rm -rf venv
# now lets create a new venv with the specified python exec
virtualenv --python=/usr/local/opt/python@3.8/bin/python3 venv
# activate the venv
source venv/bin/activate
``` 

Its also always a good idea to take a look what homebrew is saying after install because they sometimes mention on how to symlink stuff.

If this still doesnt work we can try to fix this via a quick jitsi call.

I am going to read https://docs.brew.sh/Homebrew-and-Python as this is indeed a common problem under OSX (and also maybe the reason why I always avoid this stuff by using docker) and maybe consider using https://github.com/pyenv/pyenv instead.

**Comment by telephon** [comment]
OK, this solved it – thank you!
