### ISSUE TITLE
FFT?

### ISSUE THREAD

**Issue by telephon** [capital-G/musikinformatik-sose2021#40]
might be interesting?
https://sidsite.com/posts/fourier-nets/

**Comment by capital-G** [comment]
I think FFT is really interesting but also quite a complex topic as it requires knowledge of complex numbers.
On the other hand I don't understand the post because its trivial that a NN can learn FFT - thats the reason why they are used so much as they can learn non-linear processing. Although the formalism of this post is really neat

**Comment by telephon** [comment]
The complex numbers are only convenience, one can directly use the parameters of a sine function, can't one? Or in fact it could be any function that one could try as a basis?

**Comment by capital-G** [comment]
closed via #45
